# Generated by Django 4.1.7 on 2023-02-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_survey_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='allow_multiple_responses',
            field=models.BooleanField(default=False, help_text='When checked, a user will always create a new response, regardless of editable answers.'),
        ),
    ]
