# Generated by Django 4.1.7 on 2023-03-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_survey_allow_multiple_responses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='allow_multiple_responses',
            field=models.BooleanField(default=False, help_text='When checked, a user will always create a new response and disable editable answers.'),
        ),
    ]
