# Generated by Django 4.1.7 on 2023-03-31 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_alter_survey_allow_multiple_responses'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='body_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='answer',
            name='body_en',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='answer',
            name='body_es',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='answer',
            name='body_hr',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='answer',
            name='body_ko',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='answer',
            name='body_pl',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='answer',
            name='body_ro',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='answer',
            name='body_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='answer',
            name='body_vi',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='answer',
            name='body_zh_cn',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ar',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_es',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_hr',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ko',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_pl',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ro',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_vi',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_zh_cn',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(max_length=400, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=400, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es',
            field=models.CharField(max_length=400, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_hr',
            field=models.CharField(max_length=400, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ko',
            field=models.CharField(max_length=400, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_pl',
            field=models.CharField(max_length=400, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ro',
            field=models.CharField(max_length=400, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=400, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_vi',
            field=models.CharField(max_length=400, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_zh_cn',
            field=models.CharField(max_length=400, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='question',
            name='choices_ar',
            field=models.TextField(blank=True, help_text="The choices field is only used if the question type\nif the question type is 'radio', 'select', or\n'select multiple' provide a comma-separated list of\noptions for this question .", null=True, verbose_name='Choices'),
        ),
        migrations.AddField(
            model_name='question',
            name='choices_en',
            field=models.TextField(blank=True, help_text="The choices field is only used if the question type\nif the question type is 'radio', 'select', or\n'select multiple' provide a comma-separated list of\noptions for this question .", null=True, verbose_name='Choices'),
        ),
        migrations.AddField(
            model_name='question',
            name='choices_es',
            field=models.TextField(blank=True, help_text="The choices field is only used if the question type\nif the question type is 'radio', 'select', or\n'select multiple' provide a comma-separated list of\noptions for this question .", null=True, verbose_name='Choices'),
        ),
        migrations.AddField(
            model_name='question',
            name='choices_hr',
            field=models.TextField(blank=True, help_text="The choices field is only used if the question type\nif the question type is 'radio', 'select', or\n'select multiple' provide a comma-separated list of\noptions for this question .", null=True, verbose_name='Choices'),
        ),
        migrations.AddField(
            model_name='question',
            name='choices_ko',
            field=models.TextField(blank=True, help_text="The choices field is only used if the question type\nif the question type is 'radio', 'select', or\n'select multiple' provide a comma-separated list of\noptions for this question .", null=True, verbose_name='Choices'),
        ),
        migrations.AddField(
            model_name='question',
            name='choices_pl',
            field=models.TextField(blank=True, help_text="The choices field is only used if the question type\nif the question type is 'radio', 'select', or\n'select multiple' provide a comma-separated list of\noptions for this question .", null=True, verbose_name='Choices'),
        ),
        migrations.AddField(
            model_name='question',
            name='choices_ro',
            field=models.TextField(blank=True, help_text="The choices field is only used if the question type\nif the question type is 'radio', 'select', or\n'select multiple' provide a comma-separated list of\noptions for this question .", null=True, verbose_name='Choices'),
        ),
        migrations.AddField(
            model_name='question',
            name='choices_ru',
            field=models.TextField(blank=True, help_text="The choices field is only used if the question type\nif the question type is 'radio', 'select', or\n'select multiple' provide a comma-separated list of\noptions for this question .", null=True, verbose_name='Choices'),
        ),
        migrations.AddField(
            model_name='question',
            name='choices_vi',
            field=models.TextField(blank=True, help_text="The choices field is only used if the question type\nif the question type is 'radio', 'select', or\n'select multiple' provide a comma-separated list of\noptions for this question .", null=True, verbose_name='Choices'),
        ),
        migrations.AddField(
            model_name='question',
            name='choices_zh_cn',
            field=models.TextField(blank=True, help_text="The choices field is only used if the question type\nif the question type is 'radio', 'select', or\n'select multiple' provide a comma-separated list of\noptions for this question .", null=True, verbose_name='Choices'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_ar',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_es',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_hr',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_ko',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_pl',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_ro',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_vi',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_zh_cn',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='survey',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='survey',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='survey',
            name='description_es',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='survey',
            name='description_hr',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='survey',
            name='description_ko',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='survey',
            name='description_pl',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='survey',
            name='description_ro',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='survey',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='survey',
            name='description_vi',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='survey',
            name='description_zh_cn',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='survey',
            name='name_ar',
            field=models.CharField(max_length=400, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='survey',
            name='name_en',
            field=models.CharField(max_length=400, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='survey',
            name='name_es',
            field=models.CharField(max_length=400, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='survey',
            name='name_hr',
            field=models.CharField(max_length=400, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='survey',
            name='name_ko',
            field=models.CharField(max_length=400, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='survey',
            name='name_pl',
            field=models.CharField(max_length=400, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='survey',
            name='name_ro',
            field=models.CharField(max_length=400, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='survey',
            name='name_ru',
            field=models.CharField(max_length=400, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='survey',
            name='name_vi',
            field=models.CharField(max_length=400, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='survey',
            name='name_zh_cn',
            field=models.CharField(max_length=400, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
    ]
