# Generated by Django 4.1.7 on 2023-04-12 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_answer_body_ar_answer_body_en_answer_body_es_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='body_zh_cn',
            new_name='body_zh_hans',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='description_zh_cn',
            new_name='description_zh_hans',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_zh_cn',
            new_name='name_zh_hans',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='choices_zh_cn',
            new_name='choices_zh_hans',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text_zh_cn',
            new_name='text_zh_hans',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='description_zh_cn',
            new_name='description_zh_hans',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='name_zh_cn',
            new_name='name_zh_hans',
        ),
    ]
