# Generated by Django 4.1.7 on 2023-03-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_category_description_ar_category_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='body_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='answer',
            name='body_en',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='answer',
            name='body_es',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='answer',
            name='body_hr',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='answer',
            name='body_ko',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='answer',
            name='body_pl',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='answer',
            name='body_ro',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='answer',
            name='body_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='answer',
            name='body_vi',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='answer',
            name='body_zh_cn',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
    ]
